sudo: false
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
  - master
before_script:
  - npm install yaspeller -g
  - cargo install mdbook || true
script:
  - yaspeller -c common-configs/.yaspellerrc --only-errors rust-by-example-ru/src/**/*.md
  - mdbook build rust-by-example-ru
  - mdbook test rust-by-example-ru
